### ISSUE TITLE
UserAssignedIdentity fails with "got multiple values for argument 'resource_name'

### ISSUE THREAD

**Issue by davejhahn** [pulumi/pulumi-azure-native#1148]
Creating a user managed identity fails with ```got multiple values for argument 'resource_name'```

## Steps to reproduce
1. Create a user managed identity

Expected: User managed identity is created
Actual: Fails with ```got multiple values for argument 'resource_name'```

Example:
```user_assigned_identity = azure_native.managedidentity.UserAssignedIdentity("id-myidentity",resource_group_name=rg.name,resource_name="my-identity-name")```

Where "rg" is previously created.

```
    TypeError: __init__() got multiple values for argument 'resource_name'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

The documentation shows:

```
user_assigned_identity = azure_native.managedidentity.UserAssignedIdentity("userAssignedIdentity",
    location="eastus",
    resource_group_name="rgName",
    resource_name="resourceName",
    tags={
        "key1": "value1",
        "key2": "value2",
    })
```

So it seems to be pretty straightforward, not sure if I'm missing something?

**Comment by davejhahn** [comment]
Looked at the source, it seems that the parameter name is actually "resource_name_" not "resource_name".   Using "resource_name_" works fine, but assuming that was not intentional.

**Comment by mikhailshilkov** [comment]
I think this is "by design": the Python SDK generation renames every parameter called `resource_name` to `resource_name_` to avoid name conflict with the logical resource name. Note that you can use an [arguments type](https://github.com/pulumi/pulumi-azure-native/blob/0c115503fda5d17143e784025749eb48b3caaf65/sdk/python/pulumi_azure_native/managedidentity/user_assigned_identity.py#L14) instead of named parameters and avoid this problem.

**Comment by turagittech** [comment]
If you do the first version which I've shown below rather than the second it'll generate an MI with the name you've created, plus some extra characters. 
It seems to be confused between the label and the resource_name parameter. The problem is that it's including the additional characters in the resource name, which means it's ignoring the resource_name value. That is a PITA for keeping resource names to our conventions and using them elsewhere in other projects. 

This behaviour is different to all other Pulumi  classes I've utilised so far, so I'll disagree that it's by design 

` 
user_assigned_identity_adf \
    = azure_native.managedidentity.UserAssignedIdentity(resource_name="RS1",
                                                        location="AustraliaEast",
                                                        resource_group_name="RG1",

                                                        tags={
                                                            "Company": "Company Group",
                                                            "ENVCODE": "DEV",
                                                            "Environment": "Development",
                                                        })

user_assigned_identity_adf \
    = azure_native.managedidentity.UserAssignedIdentity("RS1"
	resource_name="RS1",
                                                        location="AustraliaEast",
                                                        resource_group_name="RG1
                                                        tags={
                                                            "Company": "Company Group",
                                                            "ENVCODE": "DEV",
                                                            "Environment": "Development",
                                                        })
`
