### ISSUE TITLE
Support for "Allow trusted Microsoft Services" in Event Hub Namespace networking restrictions

### ISSUE THREAD

**Issue by vavsab** [pulumi/pulumi-azure-native#1152]
## Description
Event Hub Namespace supports to open the firewall for trusted Microsoft Services. This should be possible to set through Terraform as well

![image](https://user-images.githubusercontent.com/10233442/133810527-5a892d78-6545-41c7-ba67-06319b551d37.png)
(Copied from [corresponding solved Terraform issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/7104))

## Affected area
[NamespaceNetworkRuleSet](https://www.pulumi.com/docs/reference/pkg/azure-native/eventhub/namespacenetworkruleset/)

**Comment by mikhailshilkov** [comment]
It looks like it's available in the latest preview versions, e.g. https://github.com/pulumi/pulumi-azure-native/blob/fe6a237e74ec2003b339ff3ae593c000132938ab/sdk/nodejs/eventhub/v20210101preview/namespaceNetworkRuleSet.ts#L57

You would need to import `NamespaceNetworkRuleSet` from the versioned namespace instead of the default one.

**Comment by vavsab** [comment]
Works like a charm. Thanks a lot!
