### ISSUE TITLE
Changing "identity" of SQL Server resource causes it to be replaced

### ISSUE THREAD

**Issue by davecluderay** [pulumi/pulumi-azure-native#1304]
### Steps to reproduce

See the [C# project attached](https://github.com/pulumi/pulumi-azure-native/files/7560537/sqltest.zip), which has an `assign_sql_server_identity` boolean config value.
Toggling the config value causes the _SQL Server_ resource's identity to change (from assigned to unassigned, or vice versa).
e.g.
```
pulumi config set assign_sql_server_identity false
pulumi up
```

### Expected result

The resource is **updated**.

### Actual result

The resource is **replaced** (databases are lost).

**Comment by mikhailshilkov** [comment]
Hi @davecluderay This is expected behavior. Azure Open API spec marks this property as create-read only, which means it can't be updated in place: https://github.com/Azure/azure-rest-api-specs/blob/11f5ca6d6d851a18db4ebaa0b2618420dd661d00/specification/sql/resource-manager/Microsoft.Sql/preview/2020-11-01-preview/Servers.json#L700-L706

**Comment by davecluderay** [comment]
OK, thanks - so I guess this is a problem with the REST API.

**Comment by mikhailshilkov** [comment]
I think so. I'll go ahead and close the issue as I don't see any todo items on our side. Feel free to circle back if you still have questions later on.
