### ISSUE TITLE
Cannot implicitly convert type 'Pulumi.Output<string>' to 'string' on GetSecretArgs

### ISSUE THREAD

**Issue by sturlath** [pulumi/pulumi-azure-native#1440]
I can't set ResourceGroupName and VaultName  (I don´t know how at least) becuase of this error.

```csharp
  var getSecretResult = await AzureNative.KeyVault.GetSecret.InvokeAsync(new AzureNative.KeyVault.GetSecretArgs()
  {
      ResourceGroupName = ResourceGroup.Apply(t => t.Name),
      SecretName = "connectionString-secret",
      VaultName = KeyVault.Name
  });
```

This works in other places but ResourceGroupName and VaultName are string but not input here.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/2386572/150361797-8627c1e3-6ba0-4e25-a4bf-aedd15cf52f3.png">

How should I use this?

**Comment by danielrbradley** [comment]
If you want to use inputs within the args, you can use the `GetSecret.Invoke(...)` variation instead which returns an `Output<GetSecretResult>` rather than a Task which should then be able to be accessed using `.Apply()` within the `Output.Format(...)` in the same way as you already have.

Feel free to re-open if this doesn't solve your issue.
