### ISSUE TITLE
Support for Azure Database for PostgreSQL Flexible Server

### ISSUE THREAD

**Issue by vartia** [pulumi/pulumi-azure-native#1455]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Azure Database for PostgreSQL Flexible Server is not supported in [dbforpostgresql](https://www.pulumi.com/registry/packages/azure-native/api-docs/dbforpostgresql/). PostgreSQL Flexible Server has been [GA since 30.11.2021](https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/azure-database-for-postgresql-flexible-server-is-now-ga/ba-p/2987030). 

I don't see that the [preview versions of the SDK](https://github.com/pulumi/pulumi-azure-native/tree/master/sdk/python/pulumi_azure_native/dbforpostgresql) supports the latest requirements so those cannot be used to deploy PostgreSQL Flexible Server.

**Comment by viveklak** [comment]
Sigh.. its called server I believe in the API spec: see https://github.com/pulumi/pulumi-azure-native/issues/684

Available here: https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/python/pulumi_azure_native/dbforpostgresql/v20210601/server.py

**Comment by ms-lolo** [comment]
@viveklak / @vartia I think I'm struggling in similar ways. We're trying to create a MySQL flexible server but see nothing related to it in the documentation. Azure has normal servers and flexible servers and I only seem to be able to create single servers. What am I missing? Are there specific ServerArgs that would trigger the creation of a flexible server instead of a single server? Any help would be appreciated!
