### ISSUE TITLE
golang: FirewallPolicy example is wrong and not working

### ISSUE THREAD

**Issue by mblaschke** [pulumi/pulumi-azure-native#1922]
### What happened?

example in https://www.pulumi.com/registry/packages/azure-native/api-docs/network/firewallpolicyrulecollectiongroup/ is not working when using RuleCollections

there is no `pulumi.AnyArray` and `pulumi.Array` doesn't accept `network.FirewallPolicyFilterRuleCollection{}`

### Steps to reproduce

try the example

### Expected Behavior

example is working

### Actual Behavior

doesn't compile

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mblaschke** [comment]
this seems to do the trick:
```go
_, err := network.NewFirewallPolicyRuleCollectionGroup(
	ctx,
	"name",
	&network.FirewallPolicyRuleCollectionGroupArgs{
		RuleCollectionGroupName: pulumi.String("name"),
		FirewallPolicyName:      pulumi.String("firewallpolicy"),
		Priority:                pulumi.Int(100),
		ResourceGroupName:       pulumi.String("rg"),
		RuleCollections:         pulumi.ToArray(
			[]interface{}{
				network.FirewallPolicyFilterRuleCollection{
					// ...
				},
			},
		),
	},
)
```

**Comment by lblackstone** [comment]
Sorry for the bad example, and glad to see that you figured out the correct type. It looks like the code generation bug is being tracked here: https://github.com/pulumi/pulumi/issues/8072

**Comment by Zaid-Ajaj** [comment]
I've been investigating this, the real issue here is that from the users perspective `RuleCollections` has type `pulumi.ArrayInput` accepting only non-plain values but the allowed types are only generated in their _plain_ form. The type `FirewallPolicyFilterRuleCollection` should have a corresponding `FirewallPolicyFilterRuleCollectionArgs` type in the SDK that can be used in the array but the SDK is missing some these types now.
