### ISSUE TITLE
Missing storage account property `publicNetworkAccess` from docs and latest

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-azure-native#1995]
### What happened?

If you try create a storage account and use the `publicNetworkAccess: "false"` property, which is available as of 2022-05-01, you can only leverage it if you explicitly use the API version.

In addition to this, it doesn't appear in the azure-native docs: https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/storageaccount/#inputs

### Steps to reproduce

Try and create a storage account like so:

```
import * as storage from "@pulumi/azure-native/storage

const storageAccount = new storage.StorageAccount("sa", {
    resourceGroupName: resourceGroup.name,
    sku: {
        name: storage.SkuName.Standard_LRS,
    },
    kind: storage.Kind.StorageV2,
    publicNetworkAccess: "false" // this isn't in the latest spec
});
```

However if you use the explicit versioned import:

```
import * as storage from "@pulumi/azure-native/storage/v20220501";
```

It is

### Expected Behavior

`publicNetworkAccess` is available in the default API spec

### Actual Behavior

It isn't

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
This is because the current top-level namespace is pinned to `2021-02-01`. You can see the same in the docs as well:
<img width="775" alt="Screen Shot 2022-09-27 at 2 21 44 PM" src="https://user-images.githubusercontent.com/1094518/192637995-d8085138-1ab8-4440-8494-df4a9c078626.png">
I expect this to move at the time of the next major release of azure-native but at the moment we are pinned to that api version unless you use the versioned api.

Due to the scale of this provider we only generate docs for the top level namespace in the registry.

**Comment by danielrbradley** [comment]
Agreed, this is currently by design that we haven't moved to the latest version as it includes breaking changes. This will be addressed at the point we cut the V2 release.
