### ISSUE TITLE
Support oidc-issuer in AKS

### ISSUE THREAD

**Issue by houssems** [pulumi/pulumi-azure-native#2060]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
We are implementing the new Azure AD Workload identity in our AKS. This one replaces the old AAD pod identity.  For this an option called oidc-issuer must be activated.

In Az command there is 
`  az aks update \
    --name $aksClusterName \
    --resource-group $aksResourceGroupName \
    --enable-oidc-issuer`

Is there an equivalent for this in pulumi native azure?

https://learn.microsoft.com/en-us/samples/azure-samples/azure-ad-workload-identity/azure-ad-workload-identity/

**Comment by viveklak** [comment]
Thanks for opening the issue. Passing to @thomas11 and @danielrbradley for evaluation/prioritization.

**Comment by thomas11** [comment]
Hi @houssems, since the OIDC issuer functionality is still rather new, you need to explicitly use a newer Azure API version than the default one. You can do this using the Pulumi native provider by importing the corresponding package. For instance, in Go, instead of importing `"github.com/pulumi/pulumi-azure-native/sdk/go/azure/containerservice"` you would import `"github.com/pulumi/pulumi-azure-native/sdk/go/azure/containerservice/v20220902preview"`.

In this version, `ManagedCluster` has a property `OidcIssuerProfile`.

**Comment by mdhomer** [comment]
Hi @thomas11, I was able to track the OIDC settings using a later azure-native version and the provider you mentioned. Any idea when this will be included with the general releases?

**Comment by thomas11** [comment]
Hi @mdhomer, glad it works for you!

All the Azure API versions that are included in our provider SDK come directly from Microsoft, and you can consider them general release from the Pulumi side.

Regarding the "preview" in the API version, that comes directly from Microsoft. Checking on ManagedCluster again, it seems there's now a stable API version [V20230101](https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/ContainerService/V20230101/ManagedCluster.cs) that has `OidcIssuerProfile`.

**Comment by mdhomer** [comment]
You're right @thomas11, thanks for that update I've referenced the more up-to-date assembly V20230101 in my c# project and things look consistent :)
