### ISSUE TITLE
Missing resource for Postgres Flexible Server

### ISSUE THREAD

**Issue by fa-bwilliams** [pulumi/pulumi-azure-native#2206]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Pulumi azure-native does not contain a resource type for Postgres 'Flexible' Server. It looks like others discussed this issue a year or two ago and there was a preview that never merged and now no longer works.

### Affected area/feature
azure-native resource missing

**Comment by thomas11** [comment]
Previously: #1455. Flexible servers are confusing in Azure's API and docs. There are different endpoints for flexible vs. regular, though:
  - [Microsoft.DBforPostgreSQL/servers/{serverName}?api-version=2017-12-01](https://learn.microsoft.com/en-us/rest/api/postgresql/singleserver/servers/create?tabs=HTTP)
  - [Microsoft.DBforPostgreSQL/flexibleServers/{serverName}?api-version=2021-06-01](https://learn.microsoft.com/en-us/rest/api/postgresql/flexibleserver/servers/create?tabs=HTTP#sku)

Needs more investigation.

**Comment by fa-bwilliams** [comment]
I thought maybe the API had matured enough since the last visit to this topic. Terraform's resource works. It would be great to have it in Pulumi!

**Comment by thomas11** [comment]
Hey @fa-bwilliams, while we figure this out, note that you can pulumi-azure (also called Azure Classic) alongside azure-native. Maybe that can unblock you.

**Comment by thomas11** [comment]
Hey again @fa-bwilliams, I figured this out. I was surprised Pulumi wouldn't have this resource since our SDK is generated directly from Azure's API spec. Turns out that Microsoft, somewhat questionably, transitioned from single to flexible servers via an API version bump. Version [2017-12-01 and older have the endpoint .../servers/](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json#L37), version [2021-06-01 and onward have /flexibleServers/](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2021-06-01/postgresql.json#L37).

Sorry this is not really discoverable in the Pulumi docs, but it's an odd API design.

**Comment by mikhailshilkov** [comment]
As example of creating a Flexible Postgres server is available here: https://github.com/pulumi/pulumi-azure-native/blob/master/examples/postgres/index.ts#L38

We may want to rename that resource to FlexibleServer in 2.0...

**Comment by mikhailshilkov** [comment]
@fa-bwilliams I updated that example to the latest stable API version and tested it locally - it seems to work fine for me. See this PR: https://github.com/pulumi/pulumi-azure-native/pull/2216

**Comment by mikhailshilkov** [comment]
In 2.0, the default Server resource now points to the Flexible Server endpoint. You can read more in our migration guide: https://www.pulumi.com/registry/packages/azure-native-v2/from-v1-to-v2/#mysql-and-postgresql-server-and-flexible-server

I'll go ahead and close the issue.
