### ISSUE TITLE
@pulumi/azure-native crashes TypeScript compiler

### ISSUE THREAD

**Issue by michaellperry** [pulumi/pulumi-azure-native#2251]
I love this service! It's a joy to work on infrastructure using the languages I love.

I ran into a problem with a TypeScript project on Azure. If `@pulumi/azure-native` is installed, tsc crashes. This prevents the language support from loading in VS Code. As a result, I don't have TypeScript intellisense.

This is documented in this [GitHub issue](https://github.com/microsoft/TypeScript/issues/50809).

I'm going to try moving my project to `@pulumi/azure` as a workaround.

**Comment by aureq** [comment]
@michaellperry Glad to here you're enjoying Pulumi.

On the crash with VS Code, I had a similar issue a few weeks ago and I was able to resolve it by increasing the maximum memory for the TS Server.

In the VS Code preferences: `TypeScript` > `Tsserver: Max TS Server Memory` and set the value to `4096` (this one worked for me) or maybe higher. Then close VS Code and reopen your project (a reboot of your env may be necessary).

Let us know please.

**Comment by kpitzen** [comment]
Hi @michaellperry !  This is on our radar as one of the major improvements coming in Azure Native v2 - I'm going to mark this as "by design" for now, since the v1 spec includes every version of every resource for every API - that manifests itself in the form of poor performance (to the point that it can crash the language server in some cases).
