### ISSUE TITLE
Issues provisioning aro cluster

### ISSUE THREAD

**Issue by rprakashg-redhat** [pulumi/pulumi-azure-native#2252]
### What happened?

I'm trying to provision an ARO cluster and is running into few issues. Cluster never gets fully provisioned. Eventually times out with following error. I see the resource aro cluster but when i look at the cluster resource group I don't see no infra provisioned for network, compute and storage.

```
 azure-native:redhatopenshift:OpenShiftCluster (aro-demo):
    error: 1 error occurred:
    	* Code="InternalServerError" Message="Internal server error."

  pulumi:pulumi:Stack (create-aro-cluster-dev):
    error: update failed
    error: an unhandled error occurred: program failed:
    waiting for RPCs: rpc error: code = Unknown desc = invocation of azure-native:redhatopenshift:listOpenShiftClusterAdminCredentials returned an error: error reading from server: read tcp 127.0.0.1:63705->127.0.0.1:63702: use of closed network connection
```

### Expected Behavior

aro cluster provisioned just like when using az aro create command

### Steps to reproduce

Followed this incomplete example https://www.pulumi.com/registry/packages/azure-native/api-docs/redhatopenshift/openshiftcluster/

### Output of `pulumi about`

CLI
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.93.0
azuread       5.34.1
go            unknown

Host
OS       darwin
Version  13.2.1
Arch     x86_64

This project is written in go: executable='/usr/local/bin/go' version='go version go1.19.6 darwin/amd64'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/rprakashg-redhat
User           rprakashg-redhat
Organizations  rprakashg-redhat, rprakashg

Dependencies:
NAME                                       VERSION
github.com/pulumi/pulumi-azure-native/sdk  1.93.0
github.com/pulumi/pulumi-azuread/sdk/v5    5.34.1
github.com/pulumi/pulumi/sdk/v3            3.55.0

Pulumi locates its logs in /var/folders/68/przlt2ls6nqfyk63c7zgppl00000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rprakashg-redhat** [comment]
I think the error message is confusing in addition to the fact that its going to localhost. I see ARO cluster resource in azure but no infra provisioned.

**Comment by thomas11** [comment]
Hi @rprakashg-redhat, sorry for the failure you've encountered. The error mentions localhost because Pulumi talks to a local server via grpc.

To debug this, it would be helpful to have more logs. If it's not too much trouble or confidential, could I ask you to re-run your command like this:
```
pulumi up --logtostderr --logflow -v=9 2> out.txt
```

**Comment by rprakashg-redhat** [comment]
Ok will do that. Thanks for working with me on this. Can't wait to get this working and show to customer.

**Comment by rprakashg-redhat** [comment]
Can i email you the file? Just don't want to attach here incase there is any sensitive secrets in there

Thanks,
Ram

**Comment by rprakashg-redhat** [comment]
About reproducing the issue here is the repo https://github.com/rprakashg-redhat/create-aro-cluster
you can replace the subscriptionid, tenat in stack config to match yours and run same pulumi up. I tried to simulate the az cli commands i run to create the aro cluster with minor differences like with az cli command some of the permissions are automatically set, creation of cluster resource group etc... which i had to take care in the pulumi code as i saw in my testing got various permission related and other errors

**Comment by rprakashg-redhat** [comment]
Any update on this? @thomas11 ?

**Comment by thomas11** [comment]
Hi @rprakashg-redhat, sorry for dropping this. Unfortunately, I don't seem to have gotten your email. I can try your repro, though.

**Comment by rprakashg-redhat** [comment]
I just resend the email again that has the output after verbose logging was enabled. Yep easy to repro in your environment with the code in the repo too

**Comment by thomas11** [comment]
Hi @rprakashg-redhat, sorry for the long silence.

Using your repro is not straightforward due to the hard-coded vnet, roles, and principal ids. Any reason you didn't define those with Pulumi as well, so you could later just refer to their ids and names programmatically?

One thing I spotted in your Stack config is
```
azure:subscriptionId: ...
azure:tenantId: 
```

That won't work since the `azure:` prefix is for the classic provider. It should be `azure-native: ...`. I know this is an easy mistake to make and have [an issue](https://github.com/pulumi/pulumi-azure-native/issues/592) to make this more user-friendly.

**Comment by rprakashg-redhat** [comment]
```Using your repro is not straightforward due to the hard-coded vnet, roles, and principal ids. Any reason you didn't define those with Pulumi as well```

They are not hard coded, I am programmatically creating them in the code

**Comment by rprakashg-redhat** [comment]
assigment names are just unique guids that I generated. Only thing hard coded there is the subscription id. Do you guys have a working example?

**Comment by rquitales** [comment]
@rprakashg-redhat, I successfully spun up an ARO cluster after modifying your code. It seems that careful configuration is necessary for successful cluster creation, as failure can occur during the process.

Regarding the error `Code="InternalServerError" Message="Internal server error."` returned by Azure's API during ARO cluster creation, unfortunately, this is the only response provided by the API, offering no further helpful information. The cluster creation process typically takes around 30 minutes, and if any configuration is incorrect, the creation can fail at any point within that timeframe with a simple "Internal server error" message. It's worth noting that in general, cluster creation failures can sometimes be transient, and a subsequent attempt might succeed.

It appears that this is a well known issue has been raised multiple times in official channels. Here are a few examples: [GitHub issue 1](https://github.com/Azure/azure-rest-api-specs/issues/22514), [GitHub issue 2](https://github.com/Azure/azure-rest-api-specs/issues/23355), [GitHub issue 3](https://github.com/Azure/azure-cli/issues/16963), [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/602565/aro-creation-fails-with-internal-server-error-and), [Red Hat Customer Portal](https://access.redhat.com/solutions/6956668).

Other tool maintainers that rely on this API have also encountered the same frustration ([discussion](https://github.com/Azure/azure-rest-api-specs/issues/23355#issuecomment-1522415332)). Unfortunately, we are stuck with this situation until the ARO team improves their API and the cluster creation experience.

Regarding the second error: `waiting for RPCs: rpc error: code = Unknown desc = invocation of azure-native:redhatopenshift:listOpenShiftClusterAdminCredentials returned an error: error reading from server: read tcp 127.0.0.1:63705->127.0.0.1:63702: use of closed network connection`, this occurs when attempting to fetch the [Cluster Admin credentials](https://github.com/rprakashg-redhat/create-aro-cluster/blob/f17a94c5e0f470a0469c7284202ccfd262f7b06f/main.go#L250). It seems like if cluster creation was unsuccessful and the cluster resource exists in a failed state, fetching the admin credentials fails. The API likely tries to communicate with the kube apiserver of the cluster, but times out because the cluster is not in a ready state.

In light of these issues, I will be closing this GitHub Issue since the problem lies with the Azure API and the ARO cluster creation experience. However, if you believe there is more we can do or if you have any further insights, please feel free to reopen the issue for further discussion.
