### ISSUE TITLE
SecurityProfile "Defender" missing from ManagedCluster

### ISSUE THREAD

**Issue by AKSNewbie** [pulumi/pulumi-azure-native#2278]
Hello, i have noticed that i am unable to configure the security profile for my AKS cluster as the input seems to be missing from the API. I did come across a similar issue on the pulumi.azure api which seems to have been resolved using microsoftDefender on the resource:

https://github.com/pulumi/pulumi-azure/issues/1003

As i cannot enable this i am seeing alerts/warnings/recommendations on these resources. I guess i could do this through Azure Policy??

Anyone else trying to do this?
Thanks

**Comment by AKSNewbie** [comment]
Could i use this does anyone know?

https://www.pulumi.com/registry/packages/azure-native/api-docs/kubernetesconfiguration/extension/#inputs

**Comment by danielrbradley** [comment]
Hi @AKSNewbie The default ARM template version for the ManagedCluster is `2021-03-01`, and this property is available in any version `2022-06-01` or above. These explicit versions are all included in the SDKs, but not currently documented in the registry. Instead of importing `azure-native/container-service/ManagedCluser` you can use `azure-native/container-service/v20220601/ManagedCluster`. For reference, here's the `SecurityProfile` input property in the dotnet SDK:
https://github.com/pulumi/pulumi-azure-native/blob/8cb262ac27e539d026192c977e3ac4aedd34449e/sdk/dotnet/ContainerService/V20220601/ManagedCluster.cs#L538

I'll close as fixed as this seems to be the property you're looking for. Let us know if we've mis-understood what is missing.

**Comment by AKSNewbie** [comment]
> Hi @AKSNewbie The default ARM template version for the ManagedCluster is `2021-03-01`, and this property is available in any version `2022-06-01` or above. These explicit versions are all included in the SDKs, but not currently documented in the registry. Instead of importing `azure-native/container-service/ManagedCluser` you can use `azure-native/container-service/v20220601/ManagedCluster`. For reference, here's the `SecurityProfile` input property in the dotnet SDK:
> 
> https://github.com/pulumi/pulumi-azure-native/blob/8cb262ac27e539d026192c977e3ac4aedd34449e/sdk/dotnet/ContainerService/V20220601/ManagedCluster.cs#L538
> 
> I'll close as fixed as this seems to be the property you're looking for. Let us know if we've mis-understood what is missing.

Thanks so much - sorry i missed that :(

**Comment by danielrbradley** [comment]
No probs - glad that unblocks you :)
