### ISSUE TITLE
CosmosDB for Postgres

### ISSUE THREAD

**Issue by rhuanbarreto** [pulumi/pulumi-azure-native#2286]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Microsoft already released an API spec for CosmosDB for Postgres in https://github.com/Azure/azure-rest-api-specs/tree/main/specification/postgresqlhsc/resource-manager

How could we access it through the azure-native library?

**Comment by rquitales** [comment]
Hi @rhuanbarreto 

I'm not super familiar with Azure, but would this Pulumi resource be what you're looking for?

https://www.pulumi.com/registry/packages/azure-native/api-docs/dbforpostgresql/

**Comment by rhuanbarreto** [comment]
If you check the link I put in the issue, there are two folders sharing the same namespace:

- postgresql - https://github.com/Azure/azure-rest-api-specs/tree/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL
- **postgresqlhsc** - https://github.com/Azure/azure-rest-api-specs/tree/main/specification/postgresqlhsc/resource-manager/Microsoft.DBforPostgreSQL

So far Pulumi only supports the first one. Not the second one. Or maybe I'm missing something.

**Comment by rhuanbarreto** [comment]
Also, from https://github.com/Azure/azure-rest-api-specs/tree/main/specification/postgresqlhsc/resource-manager/Microsoft.DBforPostgreSQL folder there are two APIs supported for CosmosDB for Postgres, where the stable one (2022-11-08) is not yet implemented in the library. Most probably because only the postgresql folder was counted, not postgresqlhsc

**Comment by thomas11** [comment]
Hi @rhuanbarreto, sorry for the delay! I believe the new postgresqlhc is actually available, if you import the right API version. Microsoft made things difficult here by using the same `DBforPostgreSQL` namespace for both.

I don't what programming language you use, but in .NET, for instance, you can import `Pulumi.AzureNative.DBforPostgreSQL.V20221108` instead of just `Pulumi.AzureNative.DBforPostgreSQL`. That will give you the SDK generated for this particular version, which comes from `postgresqlhsc`.

**Comment by rhuanbarreto** [comment]
I moved into using the flexible server instead of CosmosDB for Postgres. But I will keep the issue opened in case someone has the same issue.
