### ISSUE TITLE
Azure Native 2.0 Support for Creating CNAME RecordSet and API Version '2023-07-01-preview'

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-azure-native#2589]
### What happened?

After updating to Azure Native 2.0, I encountered an issue with creating a Network/RecordSet object. It seems that the new provider has transitioned from using API version 2018-05-01 to 2023-07-01-preview. When I utilize the new API version, I receive the following error:

`code 400, {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'."`

I attempted to modify the import statement to `import { RecordSet } from '@pulumi/azure-native/network/v20180501';` However, it appears that the RecordSet member is no longer exported.

It seems that the last version in which recordSet is available in the package @pulumi/azure-native is 2.0.0-beta.1, but it disappears in version 2.0.0-beta.2.

### Expected Behavior

Expected to create an RecordSet using the latest compatible API with Azure.

### Steps to reproduce

Create an Azure Native Typescript project. Attempt to create CNAME RecordSet using Azure-Native v2.

### Output of `pulumi about`

CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mnlumi** [comment]
@zbuchheit It looks like you are referencing a beta version. Have you tried using the GA version? 2.0.0? I can see that recordset is available in 2023-07-01-preview https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/python/pulumi_azure_native/network/v20230701preview/record_set.py

**Comment by mnlumi** [comment]
Confirmed that user is working with 2.0.0. Next steps: create a repro and with `2023-07-01-preview` to and dig into the error message `{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'global' and API version`.

**Comment by fekitibi** [comment]
We are facing the same problem while attempting to create an Azure DNS Zone. The error message received is as follows:

`autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'Global' and API version '2023-07-01-preview' for type 'dnszones'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'."`

However, we need the new version 2.0.0 in order to enable DDoS protection for our public IP address. When we revert back to version 1.104.0 and attempt to create the IP protection using the "old" way, we encounter another error:

`Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"InvalidJson","message":"Could not find member 'protectedIP' on object of type 'PublicIPAddressDdosSettings'. Path 'properties.ddosSettings.protectedIP'."},{"code":"InvalidJson","message":"Could not find member 'protectionCoverage' on object of type 'PublicIPAddressDdosSettings'. Path 'properties.ddosSettings.protectionCoverage',."}]`

**Comment by dcorrea-wisr** [comment]
we are facing the same problem , unable to create new DNS records after upgrading to 2.0 . Is there a fix in progress ?

**Comment by thomas11** [comment]
Hi @dcorrea-wisr, @fekitibi, @zbuchheit, we just released v2.1.1 of the provider which fixes this issue. Please let us know if you continue to have issues, and sorry for the disruption.
