### ISSUE TITLE
Migration azure-native to v2 leads to ManagedCluster replacing

### ISSUE THREAD

**Issue by vladimirpodr** [pulumi/pulumi-azure-native#2669]
### What happened?

I am migrating from azure-native provider v1 to v2.0.3. Typescript. And for containerservice.ManagedCluster resource sku name 'Basic'  is deprecated, and I use the name value 'Base'. so that I don't do it anyway Pulumi tries to replace/redeploy cluster resource.
 I changed several deprecated parameters/values but the issue with SKU only. Look at diff outputs:
I have tried to update provider in two steps: 1.70 -> 1.104 (latest minor release) -> 2.0.3. But result the same:
```
% pulumi preview --diff

    +-azure-native:containerservice:ManagedCluster: (replace)
        [id=/subscriptions/**********/resourcegroups/rg-service-platform-sandbox/providers/Microsoft.ContainerService/managedClusters/aks-sandbox]
        [urn=urn:pulumi:sandbox::service-platform::azure-native:containerservice:ManagedCluster::aks-sandbox]
        [provider=urn:pulumi:sandbox::service-platform::pulumi:providers:azure-native::default_2_3_0::5c8310bc-fc8e-48d2-811b-d7f3ad4a2cc9]
      ~ identity         : {
          - userAssignedIdentities: {
              - /subscriptions*************/resourcegroups/rg-service-platform-sandbox/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-sandbox-identitycd3cea73: {}
            }
          + userAssignedIdentities: [
          +     [0]: "/subscriptions/**************/resourcegroups/rg-service-platform-sandbox/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-sandbox-identitycd3cea73"
            ]
        }
      ~ networkProfile   : {
          - dockerBridgeCidr: "172.17.0.0/16"
        }
      ~ sku              : {
          ~ name: "Basic" => "Base"
          ~ tier: "Paid" => "Standard"
        }
 ```

     

### Expected Behavior

pulumi up without diffs

### Steps to reproduce

change package version "@pulumi/azure-native": "^1.0.0" -> "@pulumi/azure-native": "2.3.0"
npm install
pulumi refresh
pulumi up

### Output of `pulumi about`

```
% pulumi about
CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.5.1'

Current Stack: organization/service-platform/sandbox

TYPE                                                             URN
...
azure-native:containerservice:ManagedCluster                     urn:pulumi:sandbox::service-platform::azure-native:containerservice:ManagedCluster::aks-sandbox
...

Found no pending operations associated with sandbox

Backend        
Name           Volodymyrs-MacBook-Pro.local
URL            azblob://iac-sandbox?storage_account=******
User           vladimirpodr
Organizations  

Pulumi locates its logs in /var/folders/fc/5pn3zl8x7nd2_2xk_0v1z1140000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @vladimirpodr sorry to see you've run into an issue with the upgrade.

This is quite a tricky issue as there's no quick fix here. 

## Workaround

I think that the most immediate workaround that's available is to remove this resource from your program (either editing state manually or by [setting RetainOnDelete](https://www.pulumi.com/docs/concepts/options/retainondelete/), deploying, then removing and deploying again). Once it's removed from your state you should be able to [re-import it](https://www.pulumi.com/docs/cli/commands/pulumi_import/) using the new provider. 

## Possible solution 1

Pulumi currently has arguments for specifying additional properties which require replacement, but no way to ignore properties which are causing replacement. This could hypothetically be added to the core engine but would likely take quite a long time to land in an update for azure-native.

An alternative approach could be to provide an environment variable which is specific to this azure-native provider which disables causing replacements entirely - only for the purpose of fixing specific upgrade problems like this. E.g. `PULUMI_AZURENATIVE_DISABLE_REPLACEMENTS=true`.

## Possible solution 2

To avoid the somewhat convoluted process of removing then re-importing the resource, it might be preferable to just edit the state directly. However, due to legacy reasons inputs are not easily editable in the state file because they're also serialized, encrypted and stored as an ouput called `__inputs` - which is what the replacement is calculated from. This will be solved by the following issue:
- https://github.com/pulumi/pulumi-azure-native/issues/2552

If this is implemented, the input values could just be updated to the new values in the state file, re-imported, then the upgrade deployment run.

## Possible solution 3

We could attempt to be more lienient on the replacements at the point of crossing a major version boundary. So if we see that the previous version of the provider was a different major version, then we disable all replacements. I don't know if this is currently possible as I don't think we currently have access to the version number of the previous version of the provider at the point of calculating the required replacements.

**Comment by ArgTang** [comment]
@danielrbradley 
If there will be a longer term fix than the one propose. could the last Apiversion that supports the `Basic` naming be included in the pkg? (i think that would be `V20230101`) for dotnet(and i assume other languages), we cant follow the proposed solution to import the older pkg. 

I have tried reimporting but its not working
