### ISSUE TITLE
Parity request with Azure Classic for Palo Alto resources

### ISSUE THREAD

**Issue by utku-yurter-scf** [pulumi/pulumi-azure-native#2845]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

 In Azure Classic package, there is Palo Alto resources support ([https://www.pulumi.com/registry/packages/azure/api-docs/paloalto/](https://urldefense.com/v3/__https:/www.pulumi.com/registry/packages/azure/api-docs/paloalto/__;!!OrxsNty6D4my!8GswhmXJ-WlXHX5-5p1aKv9ynF987qCcp7eZtrjh95mbzaVRr78Z9zwgTI1nDuJVfqxZREuydTR3dNPpFliB$)), however, cannot find any Palo Alto support in Azure Native.

We are using Azure Native package for everything and don't want to have to use two different packages for Azure just for Palo Alto. I am kindly requesting parity with Azure Classic for Palo Alto resources.

### Affected area/feature

- Automation API

**Comment by mikhailshilkov** [comment]
Thank you for bringing this to our attention @utku-yurter-scf 

This probably happens because Palo Alto resources are defined in the `PaloAltoNetworks.Cloudngfw` resource provider, while we only generate packages for `Microsoft.*` resource providers.

@danielrbradley @thomas11 Do you think we should include Palo Alto too?
