### ISSUE TITLE
Please bump Microsoft.App provider version to 2024-03-01

### ISSUE THREAD

**Issue by olafurnielsen** [pulumi/pulumi-azure-native#3337]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- `pulumi-azure-native` is tracking a quite old version for the `Microsoft.App` provider (Container Apps) – `2022-03-01`
- The Container Apps service is under active development and a lot of new features and improvements have been rolled out
- `2024-03-01` is the latest API version for the App provider
- Any reason not to bump to the latest version here?

### Affected area/feature

- Provider version tracking

**Comment by thomas11** [comment]
Hi @olafurnielsen, the latest API version 2024-03-01 is available as an explicit import. For instance, in .NET, instead of importing `Pulumi.AzureNative.App` you can import `Pulumi.AzureNative.App.V20240301`, and similar in other languages.

We're aware this isn't documented well currently and are tracking improvements here.

We cannot, generally, bump API versions in minor versions of the provider since they typically come with backwards-incompatible changes. We will likely release v3 of the provider some time this year with all the default API versions updated.

**Comment by olafurnielsen** [comment]
Makes sense – hadn't realized the API versions were pinned throughout the lifetime of a major release for the provider.
