### ISSUE TITLE
Support for Azure Functions Flex Consumption

### ISSUE THREAD

**Issue by nzthiago** [pulumi/pulumi-azure-native#3551]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Azure Functions [has recently introduced](https://aka.ms/flexconsumption/publicpreviewannouncement) a new hosting plan, called Flex Consumption. In Flex Consumption, many of the standard application settings and site configuration properties used in Bicep, ARM templates, and overall control plane are deprecated or have moved and shouldn't be used when automating function app resource creation. This is is documented [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#flex-consumption-plan-deprecations).

This [plan's SKU](https://learn.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code?tabs=bicep%2Cwindows%2Cdevops&pivots=flex-consumption-plan#create-the-hosting-plan) tier is 'FlexConsumption' and name 'FC1'. There is also [a brand new `functionAppConfig` section](https://learn.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code?tabs=bicep%2Cwindows%2Cdevops&pivots=flex-consumption-plan#create-the-function-app) introduced to the `site` resource. 

I am not sure if these changes break any existing support that Pulumi has for Azure Functions and if these changes need to be special cased for Pulumi to be used for creating Flex Consumption apps but raising this as a feature request for consideration. Happy to help with any questions on this.

**Comment by TechWatching** [comment]
@nzthiago Funny you ask, I've just created a Function App using the Pulumi with the Azure Native provider and it worked perfectly. I took inspiration from the bicep sample on the Azure sample repository for Flex Consumption plan: the code looks the same, just typescript instead of bicep. The only thing needed was to use the specific version of the API where the new sections were added for the function app.

I intend to publish an article on my blog with the code in a couple of days. I don't know if you would also be interested in a PR on the sample repository you have on GitHub or if you just want to keep bicep and Terraform samples there.

**Comment by thomas11** [comment]
> The only thing needed was to use the specific version of the API where the new sections were added for the function app.

Yes, this is the key. Since the functionality was recently added, it's not present in Pulumi's default API version for this resource, but you can import newer API versions. The syntax depends on your programming language, in TypeScript, for instance, it's `import * as mysql from "@pulumi/azure-native/dbformysql/v20210501";`.

**Comment by nzthiago** [comment]
Thank you both! @TechWatching just to confirm you then deployed a function to the app and it worked end to end, you saw the functions in it and was able to trigger them?

I had a concern about a note I saw [here](https://www.pulumi.com/registry/packages/azure/api-docs/appservice/functionapp/) that says `The values for AzureWebJobsStorage and FUNCTIONS_EXTENSION_VERSION will be filled by other input arguments and shouldn't be configured separately`. While AzureWebJobsStorage is still required, the FUNCTIONS_EXTENSION_VERSION is not anymore for Flex Consumption as it was replaced by a value inside functionAppConfig section in the runtime section. I was concerned this might cause some backend validation issue.

**Comment by TechWatching** [comment]
Yes, I created a new function app from a template with a basic HTTP trigger that says hello world, deployed it using the func cli, and sent an HTTP message to it to make sure it ran correctly. Everything worked correctly.

The documentation you mention is about the Azure Classic Provider, a different provider than the Azure Native provider (Azure Classic provider is this [repository](https://github.com/pulumi/pulumi-azure) which is different from this [repository](https://github.com/pulumi/pulumi-azure-native). The Azure Classic provider is a bridge from Terraform AzureRM provider, so I guess that if it works fine with the Azure RM Terraform provider (which I don't know and I did not verify) it should also work with the Pulumi Azure Classic provider.

I made it work with the Azure Native provider (native meaning is generated directly from the Azure APIs, and as a consequence has a similar API as Bicep and contains all the API versions). The documentation for the Azure Native provider is [here](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webapp/), but you won't see the new properties because the documentation only displays one  API version (as far as I know, it's not possible on the documentation to see all the API versions, I don't know @thomas11 if it's something planned but that's something missing).

I will try to find some time very soon to publish my code to some GitHub repository and an article explaining how to implement a Function App on the Flex Consumption Plan using Azure Native provider.

**Comment by davidobrien1985** [comment]
@TechWatching I used `import * as azure_native_web from "@pulumi/azure-native/web/v20231201";` to then create a Flex Consumption app like this. 
`new azure_native_web.WebApp(`scanflex-fn`,.....`

@nzthiago is working with me to figure out why in my case for example `AzureWebJobsStorage` was not automatically set and the app is not launching as expected.

**Comment by TechWatching** [comment]
Here you go @davidobrien1985 👉 https://github.com/TechWatching/AzureFunctionsFlexConsumptionPlan
I'm using a system assigned Managed Identity with the data contributor role on the blob storage, so that might not be exactly the same case as yours. I have manually set the AzureWebJobsStorage__accountName setting,

To  deploy the code, you have to be in the Function folder and run the command ` func azure functionapp publish "func-flexconsumption-dev********` (replace with the function app name coming from the functionAppName stack output)
To test everything is working correctly, make a get request on the functionEndpoint stack output.

**Comment by TechWatching** [comment]
@nzthiago @davidobrien1985 And here is the blog post: https://techwatching.dev/posts/flex-consumption-plan
I hope it can help you.

**Comment by nzthiago** [comment]
@TechWatching great write up! Thank you. I think for the purpose of this feature request (support Flex Consumption in Pulumi Azure Native) it seems to already be addressed we can close this issue. By the way, support for Azure RM Terraform provider is under development, but not quite there yet. Once it's out then it seems Pulumi Azure Classic will start working too.

**Comment by erwinkramer** [comment]
> the FUNCTIONS_EXTENSION_VERSION is not anymore for Flex Consumption as it was replaced by a value inside functionAppConfig section in the runtime section.

@nzthiago 

Removing `FUNCTIONS_EXTENSION_VERSION` breaks my function app with message `We were not able to load some functions in the list due to errors. Refresh the page to try again. See details` (no details).  Just adding `FUNCTIONS_EXTENSION_VERSION` back again with value `~4` solves it. 


This is not Pulumi related but just tested in Azure portal. 

If you look at the docs here: https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-bicep#functionsruntime - it specifies: `Function app runtime version. Example: 8 (for dotnet-isolated)` - but how is version **8** of dot net (which you should specify there) related to function runtime **4**? There is no relation and thus `FUNCTIONS_EXTENSION_VERSION` is still needed (as i've proven by breaking it).

**Comment by erwinkramer** [comment]
added link here https://github.com/Azure/azure-functions-host/issues/10714

**Comment by CrawX** [comment]
After hours of debugging, it looks like I've managed to get my Function on Flex consumption to run finally. I'm using a secured storage account with private link and user managed identities and my function wasn't starting up (exactly the same error as @flo-sch). I solved this by removing `AzureWebJobsStorage` altogether, and setting `AzureWebJobsStorage__credential`, `AzureWebJobsStorage__clientId` and `AzureWebJobsStorage__accountName`.

I have to say as soon as you use some non-straightforward features (such as private link, managed identities etc), deploying an Azure Function is quite the pain. The fact that you cannot access the logs of the host is ridiculous, Microsoft really needs to work on observability here.

As of 2025-03-11, there is one (weird) way to access some sort of host logs at least, if you go to "Support and Troubleshooting" in the function, and enter "function not starting up" in the "How can we help you box" and then select "Application issues post deployment" it will redirect you to some diagnose page. For me, there was one error, if you click on "View Details" it will show some more logs:
<img width="839" alt="Image" src="https://github.com/user-attachments/assets/9587ef79-4743-4a90-81bb-78b19ba43359" />

![Image](https://github.com/user-attachments/assets/8d913607-de80-4640-8603-325e975137d1)

![Image](https://github.com/user-attachments/assets/1010f393-c1a1-444d-9fe9-375c9bcfde82)


I hope this can help some poor soul.

**Comment by thomas11** [comment]
Thank you for reporting back and helping out others!

**Comment by dm-chelupati** [comment]
@CrawX thanks for the feedback. I totally agree with you that errors and exceptions from Functions platform components should be made visible to the user to debug especially cases where configuration errors are made. We are working on getting these out soon in AppInsights. I will update here when that is available. I would also want to meet with you to learn how to did you fix your app settings based on the exception message you saw above in diagnose and solve detector. Would you be able to meet with me for 30 mins? I can also share some additional capabilities we are planning to build to enhance Functions observability experience. You can reach out to me at dchelupati@microsoft.com if you are interested to meet.
