### ISSUE TITLE
pulumi import should only generate code for properties that are different from azure default values

### ISSUE THREAD

**Issue by otahirs** [pulumi/pulumi-azure-native#3621]
### Issue description
Importing azure resources (in this example thought cli, e.g. `pulumi import --file .\import.json `) requires specifying a lot of properties, that should instead have sane defaults instead.  
Currently if you import a resource, the generated code (and state `inputs`) contain number of specified properties that are not required for the same outcome. This all leads to having almost all properties specified in the code (for possibly hundreds of resources) which is not a convenient way to manage your infrastructure. We want to keep in the code only properties that are relevant/different from the defaults in azure and there is no documented way, how to achieve this.

### Example

see the following example with `azure-native:documentdb:DatabaseAccount`  

the generated code is
```ts
const db_account_name = new azure_native.documentdb.DatabaseAccount("db-account-name", {
    accountName: "Db-Account-Name",
    backupPolicy: {
        continuousModeProperties: {
            tier: azure_native.documentdb.ContinuousTier.Continuous30Days,
        },
        type: "Continuous",
    },
    consistencyPolicy: {
        defaultConsistencyLevel: azure_native.documentdb.DefaultConsistencyLevel.Strong,
        maxIntervalInSeconds: 5,
        maxStalenessPrefix: 100,
    },
    createMode: azure_native.documentdb.CreateMode.Default,
    databaseAccountOfferType: azure_native.documentdb.DatabaseAccountOfferType.Standard,
    defaultIdentity: "",
    disableKeyBasedMetadataWriteAccess: false,
    disableLocalAuth: false,
    enableAnalyticalStorage: false,
    enableAutomaticFailover: false,
    enableFreeTier: false,
    enableMultipleWriteLocations: false,
    enablePartitionMerge: false,
    identity: {
        type: azure_native.documentdb.ResourceIdentityType.None,
    },
    isVirtualNetworkFilterEnabled: false,
    kind: azure_native.documentdb.DatabaseAccountKind.GlobalDocumentDB,
    location: "East US",
    locations: [{
        failoverPriority: 0,
        isZoneRedundant: false,
        locationName: "East US",
    }],
    minimalTlsVersion: azure_native.documentdb.MinimalTlsVersion.Tls12,
    networkAclBypass: azure_native.documentdb.NetworkAclBypass.None,
    publicNetworkAccess: azure_native.documentdb.PublicNetworkAccess.Enabled,
    resourceGroupName: "Rg-Name",
}, {});
```

in comparison the terraform definition was something along this
```hcl
 resource "azurerm_cosmosdb_account" "db_account_name" {
  name                = var.name
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name


  offer_type = "Standard"
  kind       = "GlobalDocumentDB"

  consistency_policy {
    consistency_level = "Strong"
  }

  geo_location {
    location          = var.resource_group.location
    failover_priority = 0
  }

  backup {
    type = "Continuous"
  }
}
```
As you can see, there are so many properties that feel like default values (at least in direct comparison with terraform), that we don't want to specify in code. 

### Related issued
https://github.com/pulumi/pulumi-azure-native/issues/794
https://github.com/pulumi/pulumi/issues/5878
https://github.com/pulumi/pulumi/issues/6146
These issues describe mainly that you can't import resources (via `importId`) without specifying all (default) properties. As cli pulumi import does not block you in that regard, you can go through the import. Nonetheless, after that you still need to specify everything in code, otherwise you will see properties being deleted during the next `pulumi up`.

### Summary

During import Pulumi should only generate code (and `inputs` to the state file) for properties that are different from azure default values, at minimum there should be a documented way to achieve the same outcome.

**Comment by danielrbradley** [comment]
Hi @otahirs, thanks for reaching out and writing this up.

From what I can see, there's two distinct parts to the issue you're facing:
1. When using `importId`, Pulumi requires you to specify all arguments (https://github.com/pulumi/pulumi/issues/5878)
2. The Azure Native provider doesn't remove default values during import (https://github.com/pulumi/pulumi-azure-native/issues/2246)

I believe these two existing issues cover what you're describing and so I'll close this as a duplicate so we can keep the conversation contained in one place. I would recommending upvoting the existing issues too or adding any additional context to them that you think might help resolve the issue.

The Azure-specific issue of not removing values which are defaults is currently blocked due to Azure not having a way of indicating what the default values are. There are some simple default values in the specifications which we already use to solve this, however, most default values are set behind the Azure APIs and are not known until the point when we actually call the API to create the resource - at which point we correlate any value that was returned which we didn't specify, must be the default. We're still therefore waiting on a workable solution. 

As an alternative workaround, the Classic provider might be a good alternative to test when doing large amounts of imports as it sets its own defaults rather than relying on Azure's server-side defaults. This should allow it to present a much more minimal set of imported properties.
