### ISSUE TITLE
Add `Asynchronous_filter` to `cognitiveservices.RaiPolicyMode`?

### ISSUE THREAD

**Issue by onordberg** [pulumi/pulumi-azure-native#3792]
It seems based on the [Azure API docs](https://learn.microsoft.com/en-us/rest/api/aiservices/accountmanagement/rai-policies/create-or-update?view=rest-aiservices-accountmanagement-2024-10-01&tabs=HTTP#raipolicymode) that there is a new `RaiPolicyMode` called `Asynchronous_filter`. I am using it myself in Azure OpenAI. When setting it in the Azure OpenAI GUI it is being listed as `"mode": "Asynchronous_filter",` in the ARM template.

To me it seems based on the documentation that it could be equivalent to `Deferred`. Not sure if its on your part just a matter of implementing a new enum. Flagging it since I believe many Azure OpenAI users will be chosing this option so it is needed.

**Comment by thomas11** [comment]
Hi @onordberg, we already support it but you need to import a newer Azure API version in your program. In .NET, for instance, you would import `Pulumi.AzureNative.CognitiveServices.V20241001`, and similarly in other languages.

The Pulumi provider always keeps up with new API versions, but we can only switch the default API version in a major version since there could be breaking changes.
