### ISSUE TITLE
Azure Event Hub Network Ruleset missing properties for 2018-01-01-Preview

### ISSUE THREAD

**Issue by bantoni** [pulumi/pulumi-azure-native#581]
Hi,

after the Azure Event Hub Network Ruleset has been made available (was missing as reported here: https://github.com/pulumi/pulumi-azure-nextgen/issues/17), I now miss some properties in the Pulumi.AzureNextGen.EventHub.V20180101Preview.NamespaceNetworkRuleSetArgs class:
- trustedServiceAccessEnabled
- virtualNetworkRules

I can find them in the Microsoft Specs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/networkrulessets-preview.json

Thanks.

**Comment by mikhailshilkov** [comment]
The newer spec version 2021-11-01 does contain these properties: https://github.com/pulumi/pulumi-azure-native/blob/e7118729e3f6080e729a04d4cdceda92d48f546b/sdk/nodejs/eventhub/v20211101/namespaceNetworkRuleSet.ts#L150-L154

Since there is a workaround available, and the issue with the old version is purely upstream, I'll go ahead and close the issue with the suggestion to use the newer API version.
