### ISSUE TITLE
WebApp with SiteConfig or ClientAffinityEnabled cannot be imported

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-native#609]
There is a problem when importing web apps, since even though correctly specifying a matching site config with everything in it, pulumi reports that everything specified in the site config is marked as new / added.

Same thing if specifying a matching ClientAffinityEnabled, it is also marked as new / added and import fails.

Not specifying these properties does not feel like an options since then it the import is not verified against the configuration, right?

**Comment by PawelStadnicki** [comment]
From my experience:
in order to **import** WebApp that uses SiteConfig values I had to use Azure Classic (Terraform based) provider.
Yes, this is downside but better than any other workaround.

I believe that anything that was previously in SiteConfig has been distributed to other ARM elements (like Deployment Center/Settings for example) so there might be no more API updates unfortunately

**Comment by WillooWisp** [comment]
I have managed to handle the web app application settings and web app connection strings using these new separate resources, but is there a separate resource for managing the other properties of the site config as well (as per below)?

```
new SiteConfigArgs
{
    AlwaysOn = true,
    Http20Enabled = true,
    WebSocketsEnabled = true,
    Use32BitWorkerProcess = false,
    RemoteDebuggingEnabled = false,
    DefaultDocuments = new[] { "index.htm", "index.html" },
    //AppSettings = GetAppSettings(args, slotConfig, webAppSlotDatabaseName),
    //ConnectionStrings = GetConnectionStrings(args, slotConfig, webAppSlotDatabaseName)
}
```

One other comment, the WebAppConnectionStringsArgs is easy to work with since the Properties property is an input map of ConnStringValueTypePairArgs where the Value property also is an input. The WebAppApplicationSettingsArgs is not equally easy to work with since the Properties property is an input map of strings, instead of an input map of input of string.

The way I use it now is not optimal at all, especially since app settings tend to be quite many and dependent on outputs from other resources. The Output.Tuple method is also limited to eight values, so my limit is already reached.

```
Properties = Output.Tuple(input1, input2, input3, input4, input5, input6, input7, input8).Apply(tuple =>
{
    var (a, b, c, d, e, f, g, h) = tuple;
    return new Dictionary<string, string>(GetAppSettings(a, b, c, d, e, f, g, h, additionalArgs));
})
```

Is there a more optimal way to create the WebAppConnectionStringsArgs for multiple outputs?

**Comment by mikhailshilkov** [comment]
@WillooWisp you should be able to pass `Output<string>` as values of `InputMap<string>`. Doesn't that work for you?

**Comment by WillooWisp** [comment]
Yes, you are correct, I refactored the code.

The resource I am looking for is a match to this in my ARM template

 {
    ```
"type": "Microsoft.Web/sites/config",
    "apiVersion": "2018-11-01",
    "name": "[concat(parameters('sites_name'), '/web')]",
    "location": "North Europe",
    "dependsOn": [
        "[resourceId('Microsoft.Web/sites', parameters('sites_name'))]"
    ],
    "properties": {
        "numberOfWorkers": -1,
        "defaultDocuments": [
            "Default.htm",
            "Default.html",
            "Default.asp",
            "index.htm",
            "index.html",
            "iisstart.htm",
            "default.aspx",
            "index.php"
        ],
        "netFrameworkVersion": "v4.0"
    }
},
```

**Comment by WillooWisp** [comment]
This is the, ([API docs](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdateconfiguration).), for the missing resource

PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/config/web?api-version=2019-08-01

**Comment by WillooWisp** [comment]
@mikhailshilkov any thoughts on the above?

**Comment by WillooWisp** [comment]
@mikhailshilkov do you think I should report this as a new issue with missing resource...?

**Comment by mikhailshilkov** [comment]
@mikhailshilkov That makes sense, thank you.

**Comment by prakdevash** [comment]
@mikhailshilkov I am still facing the same issue. Would be great to have your input here! 

I am trying to import a functionapp created with azure native which includes siteconfig. 

```
const webApp = new azure.web.WebApp(
.....
    siteConfig: {
        appSettings: allAppSettings,
        acrUseManagedIdentityCreds: false,
        alwaysOn: false,
        functionAppScaleLimit: 200,
        http20Enabled: true,
        linuxFxVersion: "",
        minimumElasticInstanceCount: 0,
        numberOfWorkers: 1
   },
   {
        import: "<functionapp's importId>"
   }
)
```
But in spite of passing all the values missing in import, the `pulumi preview` still complains

`inputs to import do not match the existing resource; importing this resource will fail`
![image](https://user-images.githubusercontent.com/92103218/156186544-33b3362f-0b50-473e-b983-012904402907.png)

What I tried 
1. Export the entire stack as JSON file, remove this particular siteconfig from the specific webApp's output in the file, save and import the updated JSON file. 
2. Ran `pulumi preview` again expecting to not see the error (since the siteconfig is not in the the pulumi resource anymore). But I am getting the same error. 

Any other better workarounds to do this? Or something I am missing ? Thanks for your help :)

**Comment by mikhailshilkov** [comment]
@prakdevash I suspect https://github.com/pulumi/pulumi-azure-native/issues/609#issuecomment-744319374 is still the case.

As a workaround, have you tried importing a resource with `pulumi import` command?

cc @danielrbradley who is now more into the azure-native provider than me.

**Comment by danielrbradley** [comment]
@prakdevash another workaround to try - does it let you continue with the import if you also add an `ignore` resource option of:

```typescript
   {
        import: "<functionapp's importId>",
        ignore: "siteConfig",
   }
```

**Comment by PawelStadnicki** [comment]
> @prakdevash another workaround to try - does it let you continue with the import if you also add an `ignore` resource option of:
> 
> ```ts
>    {
>         import: "<functionapp's importId>",
>         ignore: "siteConfig",
>    }
> ```

Ignoring SiteConfig is useful in simple scenarios but it is challenging while it grows.
SiteConfig has a lot of entries that are just added "under the cover". You may have IaC code that doesn't touch it but if you want to import then suddenly it has "some values".

It is a challenge for advanced scenarios. For example, we have one code that provisions AppFunction for both "Replication" and "API" use cases.
It means we put different values in SiteConfig like AlwaysOn/MinimumElasticInstanceCount because there are different for different AppServicePlan options. SiteConfig keeps also setup up about vnets, docker, health checks to name a few.

There might be a different reason why you want to import a resource.
In our case  we had resources for DEV created via Azure portal and then wanted to propagate (copy) them to QA and PROD via IaC. 
I worked a lot with importing and must admit that it is much better and easier to delete the existing resource and recreate with Pulumi..

**Comment by prakdevash** [comment]
So I finally managed to import the resource using the `ignoreChanges: []` option. So during the first `pulumi up`, no warning are thrown and the properties are ignored as expected. The ignored properties gets updated when we run `pulumi up` again after removing imports.

**Comment by danielrbradley** [comment]
@prakdevash glad to hear that got you working with the temporary ignores during import.

@PawelStadnicki this shouldn't be a perminant ignore, just temporarily while doing the import process. The site config should be able to be un-ignored after.

Closing as the ignore process or separate resource routes are able to solve the issue.
