### ISSUE TITLE
Issues with Template and Parameters properties of DeploymentPropertiesArgs 

### ISSUE THREAD

**Issue by DaRosenberg** [pulumi/pulumi-azure-native#640]
The XML docs (IntelliSense) for these two properties are incorrect and misleading:

```cs
// It can be a JObject or a well formed JSON string.
```

Neither works. According to @mikhailshilkov they both expect a `Dictionary<string, object>`.

Having to pass the `Parameters` as a dictionary is OK.

But having to pass a whole ARM template as a dictionary is unreasonably cumbersome.

## Expected behavior

- Both properties should be correctly described in their XML docs in terms of what types and values they expect
- The `Template` property really needs to be able to accept a JSON string at the very least, preferably also a `JsonDocument` or `JObject`

## Current behavior

Described above.

## Steps to reproduce

N/A

## Context (Environment)

Trying to migrate out programs to Azure.Native provider. We used some `TemplateDeployment` resources with the old provider (and still need to use at least one with the new provider).

## Affected feature

.NET with Azure.Native provider.

**Comment by DaRosenberg** [comment]
Another thing I noticed while trying to work around this:

For the `Parameters` dictionary, you also now have to “wrap” each value, from this:

```json
"sku": "Dynamic",
"skuCode": "Y1",
```

into this:

```json
"sku": {
  "value": "Dynamic"
},
"skuCode": {
  "value": "Y1"
},
```

in order to match what ARM expects.

I think it would be a huge improvement if the new provider did this for you (like the old one did).

**Comment by thomas11** [comment]
Revisiting this issue, it seems the types in question have changed.

`Template` is now an `interface{}` and the docs state "_It can be a JObject or well-formed JSON string._" That matches the suggestion in the issue.

`Parameters` is now a `map[string]DeploymentParameter`. The docs also state "_It can be a JObject or a well formed JSON string._" That seems off since it's a `map`. However, the map's value type `DeploymentParameter` has a `Value
interface{}` to which the docs probably apply.
