### ISSUE TITLE
Wrong Inputs for the Azure Notification Hubs Namespace

### ISSUE THREAD

**Issue by florianrusch** [pulumi/pulumi-azure-native#749]
I wanted to create an Azure Notification Hub namespace resource. I noticed that in the documentation for the resource, some outputs are defined as inputs.

https://www.pulumi.com/docs/reference/pkg/azure-native/notificationhubs/namespace/

## Expected behavior
For example, I would expect the `createdAt` and `updatedAt` attributes to not be inputs.

## Current behavior
They are displayed together with others as inputs.

## Steps to reproduce
None. Take a look at the documentation I referenced above 😉

**Comment by mikhailshilkov** [comment]
Thank you for noticing this. I opened an issue upstream https://github.com/Azure/azure-rest-api-specs/issues/13952
We'll pick the changes automatically if/when they fix this in the specs.

**Comment by mikhailshilkov** [comment]
This issue is fixed with the latest 2023-01-01-preview version that we use as the default one in 2.0 of the provider: https://github.com/Azure/azure-rest-api-specs/blob/0c4762d037f0d00d4e384add4e3d7200a2993b2c/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/preview/2023-01-01-preview/notificationhubs.json#L2544-L2555
