### ISSUE TITLE
Creating Time Series Insights environment throws InvalidRequestBody

### ISSUE THREAD

**Issue by Che0ps123** [pulumi/pulumi-azure-native#754]
Tried to create a Timeseriesinsights Environment

```
new azure_native.timeseriesinsights.Environment("tsi", {
    resourceGroupName: "rg1",
    kind: timeseriesinsights.EnvironmentKind.Gen2,
    sku: {
        name: timeseriesinsights.SkuName.L1,
        capacity: 1
    }

});
```

## Current behavior
Throws error on creation.

> azure-native:timeseriesinsights:Environment (tsi):
    error: Code="InvalidRequestBody" Message="Value cannot be null.\r\nParameter name: properties\r\nPath ''."

## Affected Version

azure-native@0.9.0 and lower

**Comment by mikhailshilkov** [comment]
@Che0ps123 thank you for reporting this.

It turns out that our code generation doesn't support this scenario properly. The `Environment` resource defines the body as a discriminated union type [`EnvironmentCreateOrUpdateParameters`](https://github.com/Azure/azure-rest-api-specs/blob/00a8ae16416473715a2960252edb89cbb802a6ea/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/stable/2020-05-15/timeseriesinsights.json#L1340) with child types `Gen1EnvironmentCreateOrUpdateParameters` and `Gen2EnvironmentCreateOrUpdateParameters`. We fail to detect this and generate the base properties only that are not enough.
