### ISSUE TITLE
Error changing principalId of RoleAssignment

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-native#771]
Updating this resource, e.g. changing principalId, throws the error below, but instead the resource should be marked for replacement right?

~ azure-native:authorization:RoleAssignment: (update)
      ~ principalId: "3763b23f-33e4-4db1-b8d9-366bf8dbdff0" => "2acecc98-54a8-4791-8db2-696a69c35460"

error: autorest/azure: Service returned an error. Status=400 Code="RoleAssignmentUpdateNotPermitted" Message="Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
error: update failed

**Comment by mikhailshilkov** [comment]
Yes, this change should probably cause a replacement instead of the in-place update.

Microsoft has annotations to mark a property as non-updatable but they barely use it. We have an additional hard-coded map [here](https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/gen/replacement.go#L9) to add extra annotations. For anyone looking to contribute, adding properties to this map would be a great "first issue" to open a PR for.

**Comment by morrell** [comment]
This should definitely trigger a replace, can we get this bumped, it is a PITA to work around.

**Comment by mikhailshilkov** [comment]
Fixed by https://github.com/pulumi/pulumi-azure-native/pull/1010
