### ISSUE TITLE
Creating Key in Vault - ForbiddenByRbac

### ISSUE THREAD

**Issue by shaunco** [pulumi/pulumi-azure-native#890]
## Steps to reproduce
We are running in to the same issue as described in https://github.com/pulumi/pulumi-azure-nextgen/issues/195

After a bunch of digging, it turns out that the Azure ARM API **always** uses RBAC, even if the Azure Key Vault is configured to use `Vault access policy` instead of `Azure role-based access control`.

To work around this, we have to manually add the AZ user we are running Pulumi as to the Azure Key Vault as an `Owner` Role Assignment - adding them as just a `Key Vault Crypto Officer` or `Contributor` is not enough, only `Owner` works.

@mikhailshilkov - I don't see anything in the example you provided that would make the `authorization.getClientConfig().objectId` an IAM `Owner` of the Azure Key Vault, so we're still at a loss for how your example works.

**Comment by mikhailshilkov** [comment]
Do you get the same error while running [this example](https://github.com/pulumi/pulumi-azure-native/tree/master/examples/keyvault)?

**Comment by thrixton** [comment]
@mikhailshilkov , I get the same error when running your example.

```
    error: cannot check existence of resource '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.KeyVault/vaults/xxx/keys/mykey': status code 400, {"error":{"code":"ForbiddenByRbac","message":"[ForbiddenByRbac (Forbidden)] Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: name=KeyVault/ManagementPlane;appid=xxx;oid=xxx;iss=https://sts.windows.net/xxx/\r\nAction: 'Microsoft.KeyVault/vaults/keys/read'\r\nResource: '/subscriptions/xxx/resourcegroups/rga6eec623/providers/microsoft.keyvault/vaults/xxx/keys/mykey'\r\nAssignment: (not found)\r\nVault: xxx;location=xxx\r\n"}}
```

**Comment by mariomeyrelles** [comment]
Hello, I have received the same error, but trying with Bicep instead of Pulumi. 

We need to take into account: 

0) Ideally try to create the Key Vault with RBAC enabled. 

1) The user who is deploying should have adequate permissions at least on the resource group level. Please check if you will need to create keys and secrets during deployment. If so, please check if there are roles applicable to your use case here: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#security

2) Perhaps the deployment will need to read and write keys and secrets. You can set the user who is deploying to "Owner" or create a custom role definition with the actions needed. Like this: https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli#creating-custom-roles and https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles

3) Please note that for secrets things are easier - the Key Vault Administrator role is sufficient to create secrets. For keys, I think we can only do this as Owner or with a custom role.

4) Please create do the role assignment / role creation before doing the actual deployment. The role change can take time to be effective.

I found also good help in this other thread that is related to Bicep and scopes. But the concepts discussed can be useful here as well: https://github.com/Azure/bicep/issues/2031

**Comment by robertwe** [comment]
I faced exactly same error using `@pulumi/azure-native` in version `1.66.0`

**Comment by danielrbradley** [comment]
I'm going to close this issues out as we don't have a reliable reproduction of the issue that we can use to fix against. Also, it's possible that this has been fixed in the interim as we do now have additional tests for working with KeyVault over OIDC (see https://github.com/pulumi/pulumi-azure-native/pull/2320)

**Comment by codethief** [comment]
I'm a bit late to the party but we've been experiencing the same issue. I will look into providing a minimal example for reproduction. In the meantime, I started a related discussion on workarounds [here](https://github.com/pulumi/pulumi/discussions/20702).
