### ISSUE TITLE
VirtualMachineRunCommandByVirtualMachine yields azure error from a retired command

### ISSUE THREAD

**Issue by BNBlake** [pulumi/pulumi-azure-native#893]
Running a powershell script command on a VM generated via azure-native yields an azure error.

## Steps to reproduce
1. ensure Microsoft.Compute is an enabled provider for your Azure subscription
2. create a VM with `VirtualMachine` on that subscription
3. run a powershell command on the VM via `VirtualMachineRunCommandByVirtualMachine`

Expected: The powershell command would preview and execute 
Actual: An error is thrown by Azure:

> Code="OperationNotAllowed" Message="The property 'runCommands' is not valid because the 'Microsoft.Compute/RunCommandPreview' feature is not enabled for this subscription."

**Comment by infin8x** [comment]
This appears to be an upstream issue, as seen here: https://github.com/Azure/azure-sdk-for-go/issues/14493. If this is fixed upstream, new versions of the Azure Native provider will automatically pick up those fixes.

**Comment by mikhailshilkov** [comment]
The `VirtualMachineRunCommandByVirtualMachine` is using a PUT endpoint (as all other resources) at `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/runCommands/{runCommandName}` [here](https://github.com/Azure/azure-rest-api-specs/blob/f4a4badda9e19dca5cab216f3dd8b45362aeb90b/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/runCommands.json#L252).

[This comment](https://github.com/Azure/azure-sdk-for-go/issues/14493#issuecomment-833821822) that @infin8x referenced above suggests that this feature is still under development (if I read it correctly?) and points to an older POST endpoint [here](https://github.com/Azure/azure-rest-api-specs/blob/f4a4badda9e19dca5cab216f3dd8b45362aeb90b/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/runCommands.json#L125). We don't model POST endpoints as resources, for example, because we wouldn't know how to delete such a "resource".

As a workaround, you can use an Azure SDK from your Pulumi program to invoke this old endpoint, as explained in https://www.pulumi.com/docs/intro/cloud-providers/azure/#easy-sdk-integration

**Comment by BNBlake** [comment]
There are only two endpoint versions that support `VirtualMachineRunCommandByVirtualMachine` and both have this issue.

**Comment by mikhailshilkov** [comment]
I believe this has been fixed in 2023-03-01 API that the provider uses by default starting with 2.0.
