### ISSUE TITLE
Provide pre-build Python wheels

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-azure-native#913]
For example python package uses about 655MB of space. Container images with pulumi consume most of our container registry storage and also network traffic is affected when a new container is created (and downloaded). It also takes huge amount of time in our CI pipelines. 

Thx for consideration

**Comment by mikhailshilkov** [comment]
Thank you for opening an issue to track this.

Do you have ideas that could help us optimize the size without loosing functionality?

**Comment by jancespivo** [comment]
I have some ideas:

- Split the package to multiple ones with the same namespace (to keep the API the same). The current package would be only container that depends on all of the new ones for backward compatibility. It is workaround but there is certainly no project that uses the whole API.
- Use zipped python packages - unfortunately with LazyLoader (that pulumi for python uses) it is possible only from python 3.10 I tested it and the resulted file had 145MB with almost no performance hit.

As a workaround we are deleting unused parts after installation (basically the result is the same as the first approach)

**Comment by danielrbradley** [comment]
Starting phase 1 of this work here: https://github.com/pulumi/pulumi-azure-native/issues/1547

**Comment by sanmai-NL** [comment]
@danielrbradley I noticed that you [only publish source distributions](https://pypi.org/project/pulumi-azure-native/#files), rather than pre-built [wheels](https://realpython.com/python-wheels/) on PyPI.:

> Source Distribution
[pulumi_azure_native-1.103.0.tar.gz ](https://files.pythonhosted.org/packages/89/7a/18c8b8e8c4d7ee690f6cd570c8dd11274bfa9a496b7888acd470cb3ef46f/pulumi_azure_native-1.103.0.tar.gz)(64.0 MB [view hashes](https://pypi.org/project/pulumi-azure-native/#copy-hash-modal-6300d628-0416-4064-a6d5-d35b371cbb30))
Uploaded Jun 3, 2023 source

Offering wheels [would address the performance efficiency requirements](https://realpython.com/python-wheels/#advantages-of-python-wheels) this issue presupposes.

**Comment by danielrbradley** [comment]
[Version 2.0.0 of the provider has now been released](https://github.com/pulumi/pulumi-azure-native/releases/tag/v2.0.0). This significantly reduces the size of all the SDKs.

I'm going to re-purpose this issue around providing pre-built wheels on PyPI.

**Comment by danielrbradley** [comment]
This was completed in:
- https://github.com/pulumi/pulumi-azure-native/issues/2778
